name: Test APK

on:
  push:
    branches: [ main, develop, Develop ]
  pull_request:
    branches: [ main, develop, Develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckOut Code
      uses: actions/checkout@v4
      
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: 17
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew
      
    - name: Test APK
      run: ./gradlew clean test
