name: Test APK

on:
  push:
    branches: [ main, develop, Develop,34-probar-la-vista-desarrollada-en-xml ]
  pull_request:
    branches: [ main, develop, Develop,34-probar-la-vista-desarrollada-en-xml ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest